# Generated by Django 5.0.6 on 2024-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles_Rights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
