# Generated by Django 5.0.6 on 2024-09-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles_Rights', '0002_rights_roles_delete_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='name',
        ),
        migrations.AddField(
            model_name='rights',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rights',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rights',
            name='ischecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rights',
            name='roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Roles_Rights.roles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rights',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rights',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
