# Generated by Django 5.0.6 on 2024-09-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roles_Rights', '0003_remove_rights_name_rights_delete_rights_edit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='ischecked',
        ),
    ]
