# Generated by Django 5.0.6 on 2024-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles_Rights', '0004_remove_rights_ischecked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rights',
            old_name='roles',
            new_name='roles_id',
        ),
        migrations.AddField(
            model_name='rights',
            name='roles_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
