# Generated by Django 5.0.6 on 2024-07-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pre_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_ApprovalBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Amenity_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Facing_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Nearby_Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Payment_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_RaiseCost_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_add_Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirm_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Project.confirm_project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_add_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('build', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carpet', models.IntegerField()),
                ('sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.IntegerField()),
                ('confirm_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Project.confirm_project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_add_PaidAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Paid_amenities/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirm_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Project.confirm_project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_add_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('confirm_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Project.confirm_project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_add_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase', models.CharField(max_length=255)),
                ('base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirm_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Project.confirm_project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_add_Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirm_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Project.confirm_project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_add_Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='amenities/')),
                ('confirm_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Project.confirm_project')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_amenity_master')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('variance', models.CharField(max_length=255)),
                ('nos', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('layout_image', models.ImageField(upload_to='layout_images/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_amenity_master')),
                ('confirm_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Project.confirm_project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_nearby_segment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_product_type')),
            ],
        ),
    ]
