# Generated by Django 5.0.6 on 2024-07-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_product_approvalbody_product_ownership_project_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('variance', models.CharField(max_length=255)),
                ('nos', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('layout_image', models.ImageField(upload_to='layout_images/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_amenity_master')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_nearby_segment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_product_type')),
            ],
        ),
    ]
