# Generated by Django 5.0.6 on 2024-07-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_project_add_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_add_Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='amenities/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project_amenity_master')),
            ],
        ),
    ]
