# Generated by Django 5.0.6 on 2024-08-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('IFSC', models.CharField(max_length=11)),
                ('account_type', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=20)),
                ('proof_image', models.ImageField(upload_to='bank_proof_images/')),
                ('epfo_no', models.CharField(blank=True, max_length=20, null=True)),
                ('epfo_state', models.CharField(blank=True, max_length=255, null=True)),
                ('epfo_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_no', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_state', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_branch', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('name', models.CharField(max_length=255)),
                ('document_no', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('issued_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company_profile',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobileno', models.IntegerField()),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_no', models.IntegerField()),
                ('date_of_joining', models.CharField(max_length=100)),
                ('date_of_leaving', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_name')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_add', models.TextField()),
                ('present_country', models.CharField(max_length=255)),
                ('present_state', models.CharField(max_length=255)),
                ('present_city', models.CharField(max_length=255)),
                ('present_pincode', models.CharField(max_length=20)),
                ('permanent_add', models.TextField()),
                ('permanent_pincode', models.CharField(max_length=20)),
                ('permanent_city', models.CharField(max_length=255)),
                ('permanent_state', models.CharField(max_length=255)),
                ('permanent_country', models.CharField(max_length=255)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_letter', models.FileField(blank=True, null=True, upload_to='joining_letters/')),
                ('joining_date', models.CharField(max_length=100)),
                ('increment_date', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion_date', models.CharField(blank=True, max_length=100, null=True)),
                ('increased_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('increased_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotion_letter', models.FileField(blank=True, null=True, upload_to='promotion_letters/')),
                ('transfer_date', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_letter', models.FileField(blank=True, null=True, upload_to='transfer_letters/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_branch_type')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_name')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_designation')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_grade')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_label')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('anniversary_date', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('any_medical_issues', models.TextField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Trainig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
    ]
