# Generated by Django 5.0.6 on 2024-09-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_profile',
            name='photo',
            field=models.ImageField(default=10, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='marklist',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
