# Generated by Django 5.0.6 on 2024-06-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0001_initial'),
        ('app1', '0008_remove_emp_company_profile_department_delete_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp_company_profile',
            new_name='Company_profile',
        ),
    ]
