# Generated by Django 5.0.6 on 2024-09-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0002_company_profile_photo_educationprofile_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
