# Generated by Django 5.0.6 on 2024-06-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0003_educationprofile_experience_familyprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='emp_id',
            new_name='employee_id',
        ),
    ]
