# Generated by Django 5.0.6 on 2024-09-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0003_alter_company_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Joining_letter',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics/certificates'),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_letter',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics/certificates'),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics/certificates'),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='marklist',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics/certificates'),
        ),
    ]
