# Generated by Django 5.0.6 on 2024-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('images', models.FileField(blank=True, null=True, upload_to='amenities/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_code', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('floor_lane', models.CharField(max_length=100)),
                ('facing', models.CharField(max_length=100)),
                ('build_up_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carpet_area', models.FileField(blank=True, null=True, upload_to='Area/')),
                ('layout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.IntegerField()),
                ('unit_costs', models.IntegerField()),
                ('selling_costs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCost_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_code', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('floor_lane', models.CharField(max_length=100)),
                ('facing', models.CharField(max_length=100)),
                ('build_up_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carpet_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('layout', models.FileField(blank=True, null=True, upload_to='layouts/')),
                ('units', models.IntegerField()),
                ('units_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('layout', models.FileField(blank=True, null=True, upload_to='layouts/')),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RaiseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raise_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
