# Generated by Django 5.0.6 on 2024-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('team_leader', models.CharField(max_length=100)),
                ('team_members', models.TextField()),
            ],
        ),
    ]
