# Generated by Django 5.0.6 on 2024-09-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_profile',
            fields=[
                ('agentid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobileno', models.IntegerField()),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_no', models.IntegerField()),
                ('date_of_joining', models.CharField(max_length=100)),
                ('date_of_leaving', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_company_profiles', to='Department.department_name')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_add', models.TextField()),
                ('present_country', models.CharField(max_length=255)),
                ('present_state', models.CharField(max_length=255)),
                ('present_city', models.CharField(max_length=255)),
                ('present_pincode', models.CharField(max_length=20)),
                ('permanent_add', models.TextField()),
                ('permanent_pincode', models.CharField(max_length=20)),
                ('permanent_city', models.CharField(max_length=255)),
                ('permanent_state', models.CharField(max_length=255)),
                ('permanent_country', models.CharField(max_length=255)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('anniversary_date', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('any_medical_issues', models.TextField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Trainig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent_Management.company_profile')),
            ],
        ),
    ]
