# Generated by Django 5.0.6 on 2024-09-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry_Bucket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Form',
        ),
    ]
