# Generated by Django 5.0.6 on 2024-06-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('mob', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('roles_rights', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Name',
            fields=[
                ('departmentid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='System_branch_details',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=255)),
                ('incorporation_no', models.CharField(max_length=255)),
                ('incorporation_age', models.CharField(max_length=255)),
                ('incorporation_date', models.DateField()),
                ('incorporation_certificate', models.FileField(blank=True, null=True, upload_to='incorporation_certificates/')),
                ('tax_certificate_details', models.TextField()),
                ('PAN', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('PIN', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('registered_office_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System_branch_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System_company_detail',
            fields=[
                ('companyid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('company_size', models.CharField(max_length=255)),
                ('incorporation_no', models.CharField(max_length=255)),
                ('incorporation_agency', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='company_certificates/')),
                ('TAX_certificate', models.FileField(blank=True, null=True, upload_to='tax_certificates/')),
                ('PAN', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('registered_office_details', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.CharField(max_length=15)),
                ('whatsappno', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System_company_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department_designation')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department_label')),
            ],
        ),
        migrations.AddField(
            model_name='department_designation',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department_name'),
        ),
        migrations.CreateModel(
            name='Emp_company_profile',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobileno', models.IntegerField()),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_no', models.IntegerField()),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('branch', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department_name')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_add', models.TextField()),
                ('present_country', models.CharField(max_length=255)),
                ('present_state', models.CharField(max_length=255)),
                ('present_city', models.CharField(max_length=255)),
                ('present_pincode', models.CharField(max_length=20)),
                ('permanent_add', models.TextField()),
                ('permanent_pincode', models.CharField(max_length=20)),
                ('permanent_city', models.CharField(max_length=255)),
                ('permanent_state', models.CharField(max_length=255)),
                ('permanent_country', models.CharField(max_length=255)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.emp_company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='System_branch_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_header', models.FileField(upload_to='letter_headers/')),
                ('letter_footer', models.FileField(upload_to='letter_footers/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_branch_details')),
            ],
        ),
        migrations.AddField(
            model_name='system_branch_details',
            name='branch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_branch_type'),
        ),
        migrations.CreateModel(
            name='System_business_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='System_brand_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('letter_header', models.ImageField(blank=True, null=True, upload_to='letter_headers/')),
                ('letter_footer', models.ImageField(blank=True, null=True, upload_to='letter_footers/')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_detail')),
            ],
        ),
        migrations.AddField(
            model_name='system_company_detail',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_type'),
        ),
        migrations.CreateModel(
            name='System_contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='System_other_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='System_social_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('URL', models.URLField()),
                ('icon', models.ImageField(upload_to='social_icons/')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Team_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(max_length=255)),
                ('team_member', models.BigIntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department_name')),
            ],
        ),
    ]
