# Generated by Django 5.0.6 on 2024-09-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_company_detail',
            old_name='date',
            new_name='incorporation_date',
        ),
        migrations.RemoveField(
            model_name='system_company_detail',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='system_company_detail',
            name='incorporation_agency',
        ),
        migrations.AddField(
            model_name='system_company_detail',
            name='incorporation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='incorporation_certificate/'),
        ),
    ]
