# Generated by Django 5.0.4 on 2024-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('mob', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
