# Generated by Django 5.0.6 on 2024-09-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_date_system_company_detail_incorporation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_company_detail',
            name='incorporation_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='incorporation_certificate/'),
        ),
    ]
