# Generated by Django 5.0.4 on 2024-04-13 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_admin_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_company_details',
            fields=[
                ('companyid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('company_type', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=255)),
                ('incorporation_no', models.CharField(max_length=255)),
                ('incorporation_agency', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('certificate', models.FileField(upload_to='company_certificates/')),
                ('TAX_certificate', models.FileField(upload_to='tax_certificates/')),
                ('PAN', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('registered_office_details', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.CharField(max_length=15)),
                ('whatsappno', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System_business_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_details')),
            ],
        ),
        migrations.CreateModel(
            name='System_brand_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.ImageField(upload_to='brand_logos/')),
                ('favicon', models.ImageField(upload_to='favicons/')),
                ('letter_header', models.ImageField(upload_to='letter_headers/')),
                ('letter_footer', models.ImageField(upload_to='letter_footers/')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_details')),
            ],
        ),
        migrations.CreateModel(
            name='System_contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_details')),
            ],
        ),
        migrations.CreateModel(
            name='System_other_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_details')),
            ],
        ),
        migrations.CreateModel(
            name='System_social_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('URL', models.URLField()),
                ('icon', models.ImageField(upload_to='social_icons/')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_details')),
            ],
        ),
    ]
