# Generated by Django 5.0.6 on 2024-06-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_system_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('present_address', models.TextField()),
                ('present_city', models.CharField(max_length=100)),
                ('present_district', models.CharField(max_length=100)),
                ('present_country', models.CharField(max_length=100)),
                ('present_pincode', models.CharField(max_length=20)),
                ('permanent_address', models.TextField()),
                ('permanent_city', models.CharField(max_length=100)),
                ('permanent_district', models.CharField(max_length=100)),
                ('permanent_country', models.CharField(max_length=100)),
                ('permanent_pincode', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
            ],
        ),
    ]
