# Generated by Django 5.0.4 on 2024-04-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_system_company_details_system_business_details_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System_brand_details',
            new_name='System_brand_detail',
        ),
        migrations.RenameModel(
            old_name='System_business_details',
            new_name='System_business_detail',
        ),
        migrations.RenameModel(
            old_name='System_company_details',
            new_name='System_company_detail',
        ),
        migrations.RenameModel(
            old_name='System_contact_details',
            new_name='System_contact_detail',
        ),
        migrations.RenameModel(
            old_name='System_other_details',
            new_name='System_other_detail',
        ),
        migrations.RenameModel(
            old_name='System_social_details',
            new_name='System_social_detail',
        ),
    ]
