# Generated by Django 5.0.4 on 2024-06-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_system_brand_details_system_brand_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('roles', models.TextField()),
                ('designation_label', models.CharField(max_length=255)),
                ('label_description', models.TextField()),
                ('grade_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp_company_profile',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobileno', models.IntegerField()),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_no', models.IntegerField()),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('branch', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_add', models.TextField()),
                ('present_country', models.CharField(max_length=255)),
                ('present_state', models.CharField(max_length=255)),
                ('present_city', models.CharField(max_length=255)),
                ('present_pincode', models.CharField(max_length=20)),
                ('permanent_add', models.TextField()),
                ('permanent_pincode', models.CharField(max_length=20)),
                ('permanent_city', models.CharField(max_length=255)),
                ('permanent_state', models.CharField(max_length=255)),
                ('permanent_country', models.CharField(max_length=255)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.emp_company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(max_length=255)),
                ('team_member', models.BigIntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
    ]
