# Generated by Django 5.0.6 on 2024-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_preprojectnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprojectnew',
            name='generate_agreement',
            field=models.FileField(blank=True, null=True, upload_to='pre_projects_agreements/'),
        ),
        migrations.AlterField(
            model_name='preprojectnew',
            name='upload_document',
            field=models.FileField(blank=True, null=True, upload_to='pre_projects_documents/'),
        ),
    ]
