# Generated by Django 5.0.6 on 2024-06-14 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_department_designation_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_company_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='system_company_detail',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.system_company_type'),
        ),
    ]
