# Generated by Django 5.0.6 on 2024-06-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_department_name_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_company_profile',
            name='department',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Emp_company_profile',
        ),
    ]
