# Generated by Django 5.0.6 on 2024-06-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_system_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_company_detail',
            name='TAX_certificate',
            field=models.FileField(blank=True, null=True, upload_to='tax_certificates/'),
        ),
        migrations.AlterField(
            model_name='system_company_detail',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificates/'),
        ),
    ]
