# Generated by Django 5.0.6 on 2024-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_emp_company_profile_department_delete_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_Board_of_Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('date_of_join', models.DateField()),
                ('date_of_leave', models.DateField(blank=True, null=True)),
                ('share', models.FloatField()),
                ('stakeholder', models.BooleanField()),
            ],
        ),
    ]
