# Generated by Django 5.0.6 on 2024-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_system_company_detail_tax_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_brand_detail',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
        migrations.AlterField(
            model_name='system_brand_detail',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
        migrations.AlterField(
            model_name='system_brand_detail',
            name='letter_footer',
            field=models.ImageField(blank=True, null=True, upload_to='letter_footers/'),
        ),
        migrations.AlterField(
            model_name='system_brand_detail',
            name='letter_header',
            field=models.ImageField(blank=True, null=True, upload_to='letter_headers/'),
        ),
    ]
