# Generated by Django 5.0.6 on 2024-07-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_system_board_of_directors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreProjectNew',
        ),
        migrations.DeleteModel(
            name='Team_management',
        ),
    ]
