# Generated by Django 5.0.6 on 2024-06-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_system_brand_detail_brand_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_branch_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
    ]
