# Generated by Django 5.0.6 on 2024-07-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_delete_preprojectnew_delete_team_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_company_detail',
            name='company_type',
        ),
        migrations.DeleteModel(
            name='System_company_type',
        ),
    ]
