# Generated by Django 5.0.6 on 2024-09-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('mob', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('present_address', models.TextField()),
                ('present_city', models.CharField(max_length=100)),
                ('present_district', models.CharField(max_length=100)),
                ('present_country', models.CharField(max_length=100)),
                ('present_pincode', models.CharField(max_length=20)),
                ('permanent_address', models.TextField()),
                ('permanent_city', models.CharField(max_length=100)),
                ('permanent_district', models.CharField(max_length=100)),
                ('permanent_country', models.CharField(max_length=100)),
                ('permanent_pincode', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('IFSC', models.CharField(max_length=11)),
                ('account_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=20)),
                ('bank_logo', models.ImageField(blank=True, null=True, upload_to='bank_logos/')),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Fixed Deposit', 'Fixed Deposit'), ('Recurring Deposit', 'Recurring Deposit'), ('NRO', 'NRO'), ('NRE', 'NRE'), ('FCNR', 'FCNR')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='System_Board_of_Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('date_of_join', models.CharField(max_length=100)),
                ('date_of_leave', models.CharField(blank=True, max_length=100, null=True)),
                ('share', models.FloatField()),
                ('stakeholder', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='System_branch_details',
            fields=[
                ('branch_name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=255)),
                ('incorporation_no', models.CharField(max_length=255)),
                ('incorporation_age', models.CharField(max_length=255)),
                ('incorporation_date', models.CharField(max_length=100)),
                ('incorporation_certificate', models.FileField(blank=True, null=True, upload_to='incorporation_certificates/')),
                ('tax_certificate_details', models.TextField()),
                ('PAN', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('PIN', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('registered_office_address', models.TextField()),
                ('branch_email', models.EmailField(max_length=254)),
                ('branch_phone', models.CharField(max_length=15)),
                ('branch_whatsapp', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System_branch_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System_company_detail',
            fields=[
                ('companyid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('company_size', models.CharField(max_length=255)),
                ('incorporation_no', models.CharField(max_length=255)),
                ('incorporation_certificate', models.ImageField(blank=True, null=True, upload_to='incorporation_certificate/')),
                ('incorporation_date', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=255)),
                ('TAX_certificate', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('registered_office_details', models.TextField()),
                ('address', models.TextField()),
                ('whatsappno', models.CharField(blank=True, max_length=15, null=True)),
                ('mobileno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='System_branch_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_branch_details')),
            ],
        ),
        migrations.CreateModel(
            name='System_branch_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_header', models.FileField(blank=True, null=True, upload_to='letter_headers/')),
                ('letter_footer', models.FileField(blank=True, null=True, upload_to='letter_footers/')),
                ('brand_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_branch_details')),
            ],
        ),
        migrations.AddField(
            model_name='system_branch_details',
            name='branch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_branch_type'),
        ),
        migrations.CreateModel(
            name='System_business_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='System_brand_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('letter_header', models.ImageField(blank=True, null=True, upload_to='letter_headers/')),
                ('letter_footer', models.ImageField(blank=True, null=True, upload_to='letter_footers/')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='System_contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='System_other_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='System_social_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_icon/')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_company_detail')),
            ],
        ),
    ]
