# Generated by Django 5.0.6 on 2024-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_social_detail',
            name='name',
        ),
        migrations.AddField(
            model_name='system_social_detail',
            name='Email',
            field=models.EmailField(default=10, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_social_detail',
            name='contact',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
