# Generated by Django 5.0.6 on 2024-09-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0002_remove_system_social_detail_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_social_detail',
            old_name='contact',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='system_social_detail',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='system_social_detail',
            old_name='icon',
            new_name='image',
        ),
    ]
