# Generated by Django 5.0.6 on 2024-09-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0003_rename_contact_system_social_detail_contact_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_branch_contact',
            old_name='contact_phone',
            new_name='contact_no',
        ),
        migrations.RemoveField(
            model_name='system_branch_contact',
            name='contact_whatsapp',
        ),
        migrations.RemoveField(
            model_name='system_branch_details',
            name='incorporation_age',
        ),
        migrations.AddField(
            model_name='system_branch_brand',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
        migrations.AddField(
            model_name='system_branch_brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
