# Generated by Django 5.0.6 on 2024-09-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0004_rename_contact_phone_system_branch_contact_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_branch_details',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='system_branch_details',
            name='company_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='System_Admin.system_company_detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_branch_details',
            name='id',
            field=models.BigAutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
