# Generated by Django 5.0.6 on 2024-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.CharField(max_length=100)),
                ('commission_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('associate', models.CharField(max_length=100)),
                ('commission_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document_for', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customer_documents/')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('associate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('associate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnquirySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('enquiry_type', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('associate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_specifications/')),
                ('specification', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document_for', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='property_documents/')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('enquiry_type', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('associate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('enquiry_type', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('associate', models.CharField(max_length=100)),
            ],
        ),
    ]
