# Generated by Django 5.0.6 on 2024-09-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Roles_Rights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Name',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department_Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_designation')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_label')),
            ],
        ),
        migrations.AddField(
            model_name='department_designation',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_name'),
        ),
        migrations.CreateModel(
            name='Department_Roles_Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('view', models.BooleanField(blank=True, default=False, null=True)),
                ('write', models.BooleanField(blank=True, default=False, null=True)),
                ('edit', models.BooleanField(blank=True, default=False, null=True)),
                ('delete', models.BooleanField(blank=True, default=False, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_name')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roles_Rights.roles')),
            ],
        ),
    ]
