# Generated by Django 5.0.6 on 2024-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_name',
            name='document_rights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
