# Generated by Django 5.0.6 on 2024-09-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
        ('Roles_Rights', '0004_remove_rights_ischecked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_designation',
            name='roles_rights',
        ),
        migrations.CreateModel(
            name='Department_Roles_Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('view', models.BooleanField(blank=True, default=False, null=True)),
                ('write', models.BooleanField(blank=True, default=False, null=True)),
                ('edit', models.BooleanField(blank=True, default=False, null=True)),
                ('delete', models.BooleanField(blank=True, default=False, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department_name')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roles_Rights.roles')),
            ],
        ),
    ]
