# Generated by Django 5.0.6 on 2024-09-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_department_name_document_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_name',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
