# Generated by Django 5.0.6 on 2024-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreProjectNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_location', models.CharField(max_length=255)),
                ('ownership_type', models.CharField(choices=[('OWN', 'Owned'), ('REN', 'Rented')], max_length=3)),
                ('project_segment', models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commercial'), ('IND', 'Industrial')], max_length=3)),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('NEW', 'New Construction'), ('REN', 'Renovation'), ('EXT', 'Extension')], max_length=3)),
                ('project_description', models.TextField()),
                ('project_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approvals', models.JSONField()),
                ('expenses', models.JSONField()),
                ('document_history', models.JSONField()),
                ('generate_agreement', models.FileField(blank=True, null=True, upload_to='pre_projects_agreements/')),
                ('upload_document', models.FileField(blank=True, null=True, upload_to='pre_projects_documents/')),
            ],
        ),
    ]
