# Generated by Django 5.0.6 on 2024-07-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pre_Project', '0002_confirm_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_project',
            name='generate_agreement',
            field=models.FileField(blank=True, null=True, upload_to='confirm_project_agreements/'),
        ),
        migrations.AlterField(
            model_name='confirm_project',
            name='upload_document',
            field=models.FileField(blank=True, null=True, upload_to='confirm_projects_documents/'),
        ),
    ]
