# Generated by Django 5.0.6 on 2024-09-25 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('enquiry_id', models.CharField(max_length=255)),
                ('quote_id', models.CharField(max_length=255)),
                ('sales_id', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('project', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('payment_receipt_number', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_payment', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255)),
                ('next_pay_date', models.DateField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medium_of_payment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('instalment_stage', models.CharField(max_length=255)),
                ('statement', models.CharField(blank=True, max_length=255)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_received', models.BooleanField(default=False)),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.paymentreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agreement_id', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('created_by', models.CharField(max_length=50)),
                ('Upload_by', models.CharField(max_length=50)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='SaleAgreement/')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.paymentreceipt')),
            ],
        ),
    ]
